
//GLOBAL PARAMETERS

//TIMING CONSTANTS FOR TIMER t
`define T  {23{1'b1}} 						// WHOLE SECOND
`define T_half  {22{1'b1}}					// HALF OF A SECOND
`define T_quarter  {21{1'b1}}				// QUARTER OF A SECOND
`define T_3quarter  {21{1'b1}} * 3		// 3/4 OF A SECOND

//TIMING CONSTANTS FOR TIMER sec_t
`define TIME_OPEN  4							// TIME REQUIRED TO OPEN DOOR
`define TIME_WAIT  5							// TIME BETWEEN END OF OPENING AND START OF CLOSING OPERATIONS
`define TIME_CLOSE  4						// TIME REQUIRED TO OPEN DOOR

//STATES
`define IDLE  0								
`define OPEN  1								
`define WAIT  2
`define CLOSE  3
`define PANIC  4

//SIZES OF REGISTERS
`define STATE_SIZE  2						// SIZE REQUIRED TO STORE ALL STATES
`define TIMER_SIZE  22						// SIZE REQUIRED TO GENERATE 1 SECOND COUNTER
`define SEC_TIMER_SIZE  2					// SIZE REQUIRED TO STORE MAXIMUM VALUE OF TIMING CONSTANTS FOR sec_t